Milestone : Basic UI
Gleennkar/OOP-School-Library pull request #4
Opened 2023-01-07 19:10 UTC by Gleennkar

## Created UI form for School Library
- Create a main.rb that define the entry point which will invoke at the end of your file
- Create an app.rb file that will serve as your console app entry-point
- Check linter errors
- Updated README.md

2023-01-07 20:08 UTC, KDlamini requested changes
### Hi @Gleennkar 🙋‍♀️,  

Great work so far! 💯 
There are some issues that you still need to work on improving your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 

✔️  Good PR title and description
✔️  Correct use of Gitflow 
✔️  No linter errors

## Required Changes ♻️
 
**Kindly look through the comments below 👇 for required changes**

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-07 20:08 UTC, KDlamini commented on main.rb
> +require_relative '.switch'
Kindly require `app` and `switch` properly. Kindly remove the dot (`.`) before each word since it is causing the following error in your application.

![image](https://user-images.githubusercontent.com/38088818/211167485-473762e4-722f-49f7-aae7-735c9204dc8f.png)

2023-01-07 20:08 UTC, KDlamini commented on app.rb
> +
***Since some of your app files do not have commits and do not appear in this pull request, I will use the `app.rb` file to comment on other files in your app.***

1. in the `teacher.rb` file you used lowercase `person` instead of capitalized `Person` to include inheritance.

![image](https://user-images.githubusercontent.com/38088818/211167622-21367891-2563-4b5f-8b32-477f26355f9b.png)

This is causing the following error. Kindly look into it.

![image](https://user-images.githubusercontent.com/38088818/211167513-e10df0ae-6c0c-448b-9029-5fa567c2b075.png)

2. Please require `person` and `books` properly in the `rental.rb` file.  Because you included dots before each word it is causing the following error.

![image](https://user-images.githubusercontent.com/38088818/211167746-09309a0b-dca9-4e4a-9dec-25c62a7f211d.png)

![image](https://user-images.githubusercontent.com/38088818/211167709-a4e70925-7068-483c-96ce-390ce1a4c4fa.png)

2023-01-07 20:08 UTC, KDlamini commented on switch.rb
> +
Same thing here. Please remove the dot when requiring `app`. It is causing an error in your application.

![image](https://user-images.githubusercontent.com/38088818/211167831-579dbed4-17b9-43f5-8e87-33b64a14d8f8.png)

2023-01-07 20:08 UTC, KDlamini commented on main.rb
> +  puts 'You Exited the App'
When I run your application nothing is displayed.

![image](https://user-images.githubusercontent.com/38088818/211167930-64155f78-f1d6-4d60-be48-5d4cdfda6712.png)

Please make sure that the application displays all the basic UI features when running `main.rb` file as an entry point. Please make sure that all the functionalities of the menu work as expected.

2023-01-08 00:44 UTC, rloterh commented on app.rb
> +
well resolved! ✔️

2023-01-08 00:50 UTC, rloterh commented on app.rb
> +      get_permision = gets.chomp.upcase
- [ ] Your app is breaking in an attempt to create a person of type student. When I enter an option (`y`) for has permission your app then throws an error. Kindly ensure to improve upon this aspect.

**Creating student person error:**
 ![image](https://user-images.githubusercontent.com/12745474/211175586-1f70e0d4-9ce4-4a01-8271-2e1caf3c46b4.png)

2023-01-08 00:50 UTC, rloterh commented on app.rb
> +                                  name))
- [ ] Similarly, your app is breaking in an attempt to create a person of type teacher. Kindly ensure to improve upon this aspect.

![image](https://user-images.githubusercontent.com/12745474/211175672-a35e68ad-95e4-4829-b51c-c45d2b7b1425.png)

2023-01-08 00:50 UTC, rloterh commented on main.rb
> +  puts 'You Exited the App'
well resolved! ✔️

2023-01-08 00:50 UTC, rloterh commented on switch.rb
> +
well resolved! ✔️

2023-01-08 00:54 UTC, rloterh requested changes
Hi Gleeny, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦    🏃‍♀️ 

## Highlights 🎯   
- Nice job applying requested fixes!

## Required Changes ♻️
_Kindly check the inline comments under the review._

## Optional suggestions 🧰 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

_Kindly check the inline comments marked **[OPTIONAL]** under the review._

**You can also consider:**
- Kindly ensure to add the _Future Features_ section to your ReadMe, which should include 1-3 potential features to be added.
- MIT license link in your ReadMe is broken, kindly endeavor to fix it.

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-08 02:52 UTC, roshan-bajgain approved these changes
Hi @Gleennkar, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-08 02:55 UTC, merged